version: '3.1'
services:
  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: diner_password
      MYSQL_DATABASE: 'react_diner'
    ports:
      - '3306:3306'
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080